/*
   listing all of the architecture that use interupts



#if defined(__arc__)||(ARDUINO_SAMD_MKR1000)||(ARDUINO_SAMD_MKRZERO)||(ARDUINO_SAMD_ZERO)\
||(ARDUINO_ARCH_SAMD)||(ARDUINO_ARCH_STM32)||(ARDUINO_STM32_STAR_OTTO)||(ARDUINO_ARCH_NRF52)\
||(ARDUINO_NANO33BLE)||(ARDUINO_ARCH_RP2040)||(ARDUINO_ARCH_ESP32)||(ARDUINO_ARCH_MBED_NANO)\
||(ARDUINO_ARCH_NRF52840)||(ARDUINO_ARCH_SAM)||(ARDUINO_ARCH_RENESAS)\
||(ARDUINO_ARCH_AVR)||(ARDUINO_AVR_UNO)||(ARDUINO_AVR_LEONARDO)||(ARDUINO_AVR_DUEMILANOVE)\
||(ARDUINO_AVR_MEGA2560)


	AVR includes:
   ARDUINO_AVR_UNO
   ARDUINO_AVR_LEONARDO
   ARDUINO_AVR_DUEMILANOVE
   DARDUINO_AVR_ESPLORA
   ARDUINO_AVR_MEGA2560
   ARDUINO_attiny

  SAM includes:


  SAMD includes:


  STM32 includes:


  NRF52 includes:


  RP2040 includes:


  

*/